# Generated by Django 2.0.5 on 2018-08-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='my default location', max_length=120, null=True),
        ),
    ]
